### ISSUE TITLE
早朝に登録された勉強会の通知が一日ずれる

### ISSUE THREAD

**Issue by kazuhito-m** [infra-workshop/bot_scripts#1]
日付を超えて「午前の浅い時間帯」に登録された勉強会が合った場合、翌日に30分前・直前通知がツイートされる。

- ![screenshot from 2018-07-08 01-48-00](https://user-images.githubusercontent.com/2945461/42413069-e227b0f8-8253-11e8-845f-766a33668094.png)
- ![screenshot from 2018-07-08 01-48-24](https://user-images.githubusercontent.com/2945461/42413071-ebd10ae6-8253-11e8-94c3-ec72623fcf66.png)
- https://twitter.com/infra_workshop/status/1015369826393452544

事実として観測できている「午前の浅い時間帯」は 08:30 までで、10:00 などだと期待通りの通知がなされている。

- https://twitter.com/infra_workshop/status/1013218127465705474

**Comment by kazuhito-m** [comment]
以下は、 擬似的に時刻 `2018/07/07 9:00:00(JST)` のタイミングで実行した場合に `post_reservation_by_at()` へ来る情報を出力したCSVである。

[20180707090000_trace.csv.txt](https://github.com/infra-workshop/bot_scripts/files/2173058/20180707090000_trace.csv.txt)

上のCSVの通りであれば、午前0〜9時までに行われる勉強会は、「翌日の同時刻に案内」されることとなると思われる。

これは、

![screenshot from 2018-07-08 05-04-39](https://user-images.githubusercontent.com/2945461/42414284-e1f76984-826c-11e8-81a1-3e40e897f191.png)

となってるからで、「日付変更線の考慮を "実行タイミング(今はおそらく9:00?)基準" で処理」する必要がある…と推測される。

※自身の推測が正しければ、「みんなでPythonを始めよう！」は、本日9:00に通知されるはず。

**Comment by 0Delta** [comment]
むっちゃ詳しい……w
ありがとうございます。

原因としては仰る通り、atコマンドの仕様として「次のX時」に発火するというものがあります。
現在9:00にBotを発火させてるため、9:00以前の勉強会については翌日のX時…となり、通知が一日ずれることになってます。
近日中に暫定対応します。

なお現在全面改修してAWS-Lambdaに対応させたVer.2を開発中です……

**Comment by 0Delta** [comment]
d795bdcf193877933caa76ef330a68ab868ef639
修正しました。
本番環境の起動タイミングはAM0:05になりました。
